### ISSUE TITLE
增加许可证提议~

### ISSUE THREAD

**Issue by EricZhou05** [dogliu666/ESurfingDialer-For-OpenWrt#1]
同学你好，很高兴能和你一起研究脚本部署，我注意到你的文章中有一些内容和我的感觉有些雷同喔，是否引用了我的文章呢。如果确实有所参考，麻烦按照规范修改你下你的文章好嘛？让我们一起维护健康的开源生态(*^▽^*)
![image](https://github.com/user-attachments/assets/b49e33e1-959e-404f-8518-d9809b1d628c)

> [许可证科普](https://github.com/phodal/licenses)

**Comment by dogliu666** [comment]
非常感谢原作者的提醒。
第一次使用GitHub上传，不熟悉相关规则，在此深感抱歉
将会改为Fork，并且会标注原作者。
最后再次深感抱歉，请原谅本小白 orz
